unit CPluginConsts;

interface

const
  //Plugin type constants
  CPLUGINTYPE_INCORRECT = 0;
  CPLUGINTYPE_CURRENCYRATE = 1;
  CPLUGINTYPE_JUSTEXECUTE = 2;
  CPLUGINTYPE_HTMLREPORT = 3;
  CPLUGINTYPE_CHARTREPORT = 4;
  CPLUGINTYPE_EXTRACTION = 5;
  CPLUGINTYPE_SELECTEDITEM = 6;

  //Series type constants
  CSERIESTYPE_PIE = 1;
  CSERIESTYPE_LINE = 2;
  CSERIESTYPE_BAR = 3;

  //Domain type constants
  CSERIESDOMAIN_DATETIME = 1;
  CSERIESDOMAIN_FLOAT = 0;

  //Currency rate types
  CCURRENCYRATE_AVG = 'A';
  CCURRENCYRATE_SELL = 'S';
  CCURRENCYRATE_BUY = 'B';

  //Extraction item types
  CEXTRACTION_INMOVEMENT = 'I';
  CEXTRACTION_OUTMOVEMENT = 'O';

  //Dialog box types
  CDIALOGBOX_WARNING = 0;
  CDIALOGBOX_ERROR = 1;
  CDIALOGBOX_INFO = 2;
  CDIALOGBOX_QUESTION = 3;

  //Selected item types
  CSELECTEDITEM_INCORRECT = 0;
  CSELECTEDITEM_BASEMOVEMENT = 256;
  CSELECTEDITEM_MOVEMENTLIST = 512;
  CSELECTEDITEM_PLANNEDDONE = 1024;
  CSELECTEDITEM_PLANNEDMOVEMENT = 2048;

implementation

end.
