unit CPluginConsts;

interface

const
  //Plugin type constants
  CPLUGINTYPE_INCORRECT = 0;
  CPLUGINTYPE_CURRENCYRATE = 1;
  CPLUGINTYPE_JUSTEXECUTE = 2;
  CPLUGINTYPE_HTMLREPORT = 3;
  CPLUGINTYPE_CHARTREPORT = 4;
  CPLUGINTYPE_EXTRACTION = 5;

  //Series type constants
  CSERIESTYPE_PIE = 1;
  CSERIESTYPE_LINE = 2;
  CSERIESTYPE_BAR = 3;

  //Domain type constants
  CSERIESDOMAIN_DATETIME = 1;
  CSERIESDOMAIN_FLOAT = 0;

  CCURRENCYRATE_AVG = 'A';
  CCURRENCYRATE_SELL = 'S';
  CCURRENCYRATE_BUY = 'B';

  CEXTRACTION_INMOVEMENT = 'I';
  CEXTRACTION_OUTMOVEMENT = 'O';

implementation

end.
